# Johannes zoomer shell

autoload -U colors && colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[cyan]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Include hidden files in autocomplete:
_comp_options+=(globdots)

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -lha --color=auto'

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

if test $TMUX; then
    bindkey '^[[1~'  beginning-of-line
    bindkey '^[[4~'  end-of-line
    bindkey '^[[3~'  delete-char
else
    bindkey '^[[H'  beginning-of-line
    bindkey '^[[F'  end-of-line
    bindkey '^[[3~'  delete-char
fi
